name: collector_flutter
description: A lightweight resource/telemetry collector for Flutter apps (FPS, jank, memory, network, events).
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  vm_service: ^14.3.1
  google_fonts: ^6.2.0
  syncfusion_flutter_charts: ^27.1.43
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
